<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>

<TargetFrameworks>net9.0-windows10.0.19041.0</TargetFrameworks>

	<UseMaui>true</UseMaui>
	<SingleProject>true</SingleProject>

	<OutputType>Exe</OutputType>
	<RootNamespace>EHMR</RootNamespace>

	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>

<!--	<ApplicationTitle>EHMR</ApplicationTitle>
	<ApplicationId>com.EHMR.mk</ApplicationId>-->

	<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
<!--	<ApplicationVersion>1</ApplicationVersion>-->

	<WindowsPackageType>None</WindowsPackageType>

	<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
	<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		    <PackageReference Include="ClosedXML" Version="0.105.0" />
		    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />

    <!-- MAUI UI TOOLKIT -->
    <PackageReference Include="CommunityToolkit.Maui" Version="12.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.8" />
		    <PackageReference Include="Microcharts.Maui" Version="1.0.1" />

    <!-- PDF REPORTS -->
    <PackageReference Include="PdfSharpCore" Version="1.3.67" />

    <!-- BARCODE / QR -->
    <PackageReference Include="ZXing.Net.Maui" Version="0.6.0" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Components\PageHeader.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Components\Search\SearchFilterBarView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\SparkDataGridView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\SparkExplorerHeaderView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\SparkStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFGridRowPresenter.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\AuthStyle - Copy.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\DashboardStyle.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFChart.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFDataGridStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFDatePickerPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFMetricTileStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFStatusChipStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFSwitchStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\ShadowFieldContainerStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFShellStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFSearchBoxStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFIconButtonStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFPaginationStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFInputStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFPickerStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFHeaderStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFCardStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFButton.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFCard.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFDataGrid.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFEntry.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFHeader.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFIconButton.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFInput.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFPagination.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFPicker.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFSearchBox.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFShell.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFStatusChip.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\FFSwitch.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\EhmrColors.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Colors.Light.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Colors.Dark.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Colors.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Controls.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\AuthStyle.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\FleetStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\ShadowDateField.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\ShadowEntryField.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\ShadowFieldContainer.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Controls\ShadowPickerField.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Layouts.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\MyStyle.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Panda.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Styles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\EhmrSizes.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Labels.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\Typography.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Appointments\AppointmentDetailPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\AppointmentListPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Calendar\CalendarDashboardPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Dashboard\DashboardView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Encounters\EncounterCreatePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Encounters\EncounterDetailPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Encounters\EncounterEditPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Encounters\EncounterListPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ErrorPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LoadingPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LoginView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MbkImportExportPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Medicine\MedicineDetailFormPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Medicine\MedicineListPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Medicine\MedicinePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\MenuView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Patients\PatientDetailFormPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Patients\PatientListPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Prescription\PrescriptionListPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ReportPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\RootLayoutPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Therapies\ProtocolDetailFormPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Therapies\ProtocolRegistryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Therapies\TherapyCyclesPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Therapies\TherapyDetailsPagе.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\UserEditPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\UsersPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Components\PageHeader.xaml.cs">
	    <DependentUpon>PageHeader.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Controls\Cells\BadgeCellView.xaml.cs">
	    <DependentUpon>BadgeCellView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Controls\Cells\ActionCellView.xaml.cs">
	    <DependentUpon>ActionCellView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Controls\Cells\HeaderCellView.xaml.cs">
	    <DependentUpon>HeaderCellView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Controls\Cells\PersonCell.xaml.cs">
	    <DependentUpon>PersonCell.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Controls\Cells\TextCellView.xaml.cs">
	    <DependentUpon>TextCellView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Controls\SparkDataGridView.xaml.cs">
	    <DependentUpon>SparkDataGridView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Controls\FFChart.xaml.cs">
	    <DependentUpon>FFChart.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Controls\FFGridRowPresenter.xaml.cs">
	    <DependentUpon>FFGridRowPresenter.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Controls\FFMetricTile.xaml.cs">
	    <DependentUpon>FFMetricTile.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\AppointmentListPage.xaml.cs">
	    <DependentUpon>AppointmentListPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Appointments\AppointmentDetailPage.xaml.cs">
	    <DependentUpon>AppointmentDetailPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Patients\PatientListPage.xaml.cs">
	    <DependentUpon>PatientListPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\RootLayoutPage.xaml.cs">
	    <DependentUpon>RootLayoutPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Therapies\ProtocolDetailFormPage.xaml.cs">
	    <DependentUpon>ProtocolDetailFormPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Therapies\ProtocolRegistryPage.xaml.cs">
	    <DependentUpon>ProtocolRegistryPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Therapies\TherapyCyclesPage.xaml.cs">
	    <DependentUpon>TherapyCyclesPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Therapies\TherapyDetailsPagе.xaml.cs">
	    <DependentUpon>TherapyDetailsPagе.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\UserEditPage.xaml.cs">
	    <DependentUpon>UserEditPage.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiFont Update="Resources\Fonts\fa-solid-900.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </MauiFont>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Domain\NewFolder\" />
	  <Folder Include="Resources\Controls\Actions\" />
	  <Folder Include="Views\Ter\" />
	</ItemGroup>

</Project>
