using EHMR.Domain.Entities;
using Microsoft.EntityFrameworkCore;

using static EHMR.Infrastructure.Persistence.DesktopTherapyDbContext;

namespace EHMR.Infrastructure.Persistence.Seeders;

public class PatientSeeder : IEntitySeeder
{
    int IEntitySeeder.Order => 8; // must run after DoctorSeeder and MedicineSeeder (Order 5)

    public async Task SeedAsync(DesktopTherapyDbContext context, CancellationToken ct = default)
    {
        var now = DateTime.UtcNow;

        var medicineIds = new[]
        {
            SeedIds.Med1, SeedIds.Med2, SeedIds.Med3, SeedIds.Med4, SeedIds.Med5,
            SeedIds.Med6, SeedIds.Med7, SeedIds.Med8, SeedIds.Med9, SeedIds.Med10
        };

        var patients = new List<Patient>
        {
            new()
            {
                Id = SeedIds.Patient1,
                DoctorId = SeedIds.Doctor1,
                FirstName = "Јетон",
                LastName = "Исмаили",
                NationalId = "0101990123456",
                SzboNumber = "SZBO-000001",
                BirthDate = new DateTime(1990, 1, 15),
                Gender = Gender.Male,
                City = "Skopje",
                Address = "ул. Илинденска 12",
                PostalCode = "1000",
                Phone = "+38970111222",
                Email = "jeton.ismaili@email.com",
                EmergencyContactName = "Фатиме Исмаили",
                EmergencyContactPhone = "+38970111223",
                EmergencyRelationship = "Сопруга",
                BloodType = "A+",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-30),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient2,
                DoctorId = SeedIds.Doctor2,
                FirstName = "Елена",
                LastName = "Петровска",
                NationalId = "1503988654321",
                SzboNumber = "SZBO-000002",
                BirthDate = new DateTime(1988, 3, 15),
                Gender = Gender.Female,
                City = "Skopje",
                Address = "бул. Партизански одреди 45",
                PostalCode = "1000",
                Phone = "+38970222333",
                Email = "elena.petrovska@email.com",
                EmergencyContactName = "Марко Петровски",
                EmergencyContactPhone = "+38970222334",
                EmergencyRelationship = "Брат",
                BloodType = "A+",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-30),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient3,
                DoctorId = SeedIds.Doctor3,
                FirstName = "Арјета",
                LastName = "Шабани",
                NationalId = "2207985112233",
                SzboNumber = "SZBO-000003",
                BirthDate = new DateTime(1985, 7, 22),
                Gender = Gender.Female,
                City = "Struga",
                Address = "ул. Кеј Македонија 8",
                PostalCode = "6330",
                Phone = "+38975333444",
                Email = "arjeta.shabani@email.com",
                EmergencyContactName = "Дритон Шабани",
                EmergencyContactPhone = "+38975333445",
                EmergencyRelationship = "Сопруг",
                BloodType = "B-",
                Allergies = "Пеницилин",
                Status = PatientStatus.Chronic,
                RegistrationDate = now.AddDays(-28),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient4,
                DoctorId = SeedIds.Doctor4,
                FirstName = "Мухарем",
                LastName = "Реџепи",
                NationalId = "0512982445566",
                SzboNumber = "SZBO-000004",
                BirthDate = new DateTime(1982, 12, 5),
                Gender = Gender.Male,
                City = "Gostivar",
                Address = "ул. Младинска 3",
                PostalCode = "1230",
                Phone = "+38970444555",
                Email = "muharem.rexhepi@email.com",
                EmergencyContactName = "Сара Реџепи",
                EmergencyContactPhone = "+38970444556",
                EmergencyRelationship = "Сопруга",
                BloodType = "O+",
                Allergies = "Прашина",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-26),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient5,
                DoctorId = SeedIds.Doctor5,
                FirstName = "Томислав",
                LastName = "Николовски",
                NationalId = "1809991778899",
                SzboNumber = "SZBO-000005",
                BirthDate = new DateTime(1991, 9, 18),
                Gender = Gender.Male,
                City = "Skopje",
                Address = "ул. 11 Октомври 21",
                PostalCode = "1000",
                Phone = "+38970555666",
                Email = "tomislav.nikolovski@email.com",
                EmergencyContactName = "Ана Николовска",
                EmergencyContactPhone = "+38970555667",
                EmergencyRelationship = "Сестра",
                BloodType = "AB+",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-24),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient6,
                DoctorId = SeedIds.Doctor6,
                FirstName = "Билјана",
                LastName = "Трајковска",
                NationalId = "2711987991122",
                SzboNumber = "SZBO-000006",
                BirthDate = new DateTime(1987, 11, 27),
                Gender = Gender.Female,
                City = "Kumanovo",
                Address = "ул. Борис Кидрич 15",
                PostalCode = "1300",
                Phone = "+38970666777",
                Email = "biljana.trajkovska@email.com",
                EmergencyContactName = "Владо Трајковски",
                EmergencyContactPhone = "+38970666778",
                EmergencyRelationship = "Сопруг",
                BloodType = "O-",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-22),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient7,
                DoctorId = SeedIds.Doctor7,
                FirstName = "Милена",
                LastName = "Стојановска",
                NationalId = "0304984223344",
                SzboNumber = "SZBO-000007",
                BirthDate = new DateTime(1984, 4, 3),
                Gender = Gender.Female,
                City = "Ohrid",
                Address = "ул. Цар Самоил 9",
                PostalCode = "6000",
                Phone = "+38975777888",
                Email = "milena.stojanovska@email.com",
                EmergencyContactName = "Петар Стојановски",
                EmergencyContactPhone = "+38975777889",
                EmergencyRelationship = "Татко",
                BloodType = "A-",
                Allergies = "Латекс",
                Status = PatientStatus.Chronic,
                RegistrationDate = now.AddDays(-20),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient8,
                DoctorId = SeedIds.Doctor8,
                FirstName = "Беким",
                LastName = "Ахмети",
                NationalId = "1902983556677",
                SzboNumber = "SZBO-000008",
                BirthDate = new DateTime(1983, 2, 19),
                Gender = Gender.Male,
                City = "Tetovo",
                Address = "ул. Илинденска 30",
                PostalCode = "1200",
                Phone = "+38970888999",
                Email = "bekim.ahmeti@email.com",
                EmergencyContactName = "Линдита Ахмети",
                EmergencyContactPhone = "+38970888990",
                EmergencyRelationship = "Сопруга",
                BloodType = "B+",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-18),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient9,
                DoctorId = SeedIds.Doctor9,
                FirstName = "Беса",
                LastName = "Красники",
                NationalId = "2606986889900",
                SzboNumber = "SZBO-000009",
                BirthDate = new DateTime(1986, 6, 26),
                Gender = Gender.Female,
                City = "Kumanovo",
                Address = "ул. Панко Брашнаров 5",
                PostalCode = "1400",
                Phone = "+38970999000",
                Email = "besa.krasniqi@email.com",
                EmergencyContactName = "Арбен Красники",
                EmergencyContactPhone = "+38970999001",
                EmergencyRelationship = "Брат",
                BloodType = "A+",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-16),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient10,
                DoctorId = SeedIds.Doctor10,
                FirstName = "Имран",
                LastName = "Османи",
                NationalId = "1408980112200",
                SzboNumber = "SZBO-000010",
                BirthDate = new DateTime(1980, 8, 14),
                Gender = Gender.Male,
                City = "Struga",
                Address = "ул. Братство Единство 2",
                PostalCode = "6330",
                Phone = "+38975000111",
                Email = "imran.osmani@email.com",
                EmergencyContactName = "Фатбарџа Османи",
                EmergencyContactPhone = "+38975000112",
                EmergencyRelationship = "Сопруга",
                BloodType = "O+",
                Allergies = "Нема",
                Status = PatientStatus.Inactive,
                RegistrationDate = now.AddDays(-14),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient11,
                DoctorId = SeedIds.Doctor1,
                FirstName = "Сара",
                LastName = "Ангелова",
                NationalId = "0705992334455",
                SzboNumber = "SZBO-000011",
                BirthDate = new DateTime(1992, 5, 7),
                Gender = Gender.Female,
                City = "Skopje",
                Address = "ул. Васил Главинов 18",
                PostalCode = "1000",
                Phone = "+38970111333",
                Email = "sara.angelova@email.com",
                EmergencyContactName = "Игор Ангелов",
                EmergencyContactPhone = "+38970111334",
                EmergencyRelationship = "Сопруг",
                BloodType = "A+",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-12),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient12,
                DoctorId = SeedIds.Doctor4,
                FirstName = "Наим",
                LastName = "Мета",
                NationalId = "1112979445566",
                SzboNumber = "SZBO-000012",
                BirthDate = new DateTime(1979, 12, 11),
                Gender = Gender.Male,
                City = "Bitola",
                Address = "ул. Климент Охридски 40",
                PostalCode = "7000",
                Phone = "+38975222444",
                Email = "naim.meta@email.com",
                EmergencyContactName = "Дрита Мета",
                EmergencyContactPhone = "+38975222445",
                EmergencyRelationship = "Сопруга",
                BloodType = "AB-",
                Allergies = "Морски плодови",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-10),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient13,
                DoctorId = SeedIds.Doctor5,
                FirstName = "Ана",
                LastName = "Георгиевска",
                NationalId = "2003994556677",
                SzboNumber = "SZBO-000013",
                BirthDate = new DateTime(1994, 3, 20),
                Gender = Gender.Female,
                City = "Prilep",
                Address = "ул. Марксова 6",
                PostalCode = "7500",
                Phone = "+38975333555",
                Email = "ana.georgievska@email.com",
                EmergencyContactName = "Филип Георгиевски",
                EmergencyContactPhone = "+38975333556",
                EmergencyRelationship = "Брат",
                BloodType = "B+",
                Allergies = "Полен",
                Status = PatientStatus.Chronic,
                RegistrationDate = now.AddDays(-9),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient14,
                DoctorId = SeedIds.Doctor4,
                FirstName = "Горан",
                LastName = "Илиевски",
                NationalId = "2909981667788",
                SzboNumber = "SZBO-000014",
                BirthDate = new DateTime(1981, 9, 29),
                Gender = Gender.Male,
                City = "Skopje",
                Address = "ул. Френклин Рузвелт 55",
                PostalCode = "1000",
                Phone = "+38970444666",
                Email = "goran.ilievski@email.com",
                EmergencyContactName = "Снежана Илиевска",
                EmergencyContactPhone = "+38970444667",
                EmergencyRelationship = "Сопруга",
                BloodType = "A+",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-8),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient15,
                DoctorId = SeedIds.Doctor4,
                FirstName = "Марија",
                LastName = "Наумовска",
                NationalId = "1601996778899",
                SzboNumber = "SZBO-000015",
                BirthDate = new DateTime(1996, 1, 16),
                Gender = Gender.Female,
                City = "Debar",
                Address = "ул. Григор Прличев 11",
                PostalCode = "6000",
                Phone = "+38975555777",
                Email = "marija.naumovska@email.com",
                EmergencyContactName = "Кире Наумовски",
                EmergencyContactPhone = "+38975555778",
                EmergencyRelationship = "Татко",
                BloodType = "O+",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-7),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient16,
                DoctorId = SeedIds.Doctor4,
                FirstName = "Дритон",
                LastName = "Бериша",
                NationalId = "0812978889900",
                SzboNumber = "SZBO-000016",
                BirthDate = new DateTime(1978, 12, 8),
                Gender = Gender.Male,
                City = "Tetovo",
                Address = "ул. Никола Карев 22",
                PostalCode = "1200",
                Phone = "+38970666888",
                Email = "driton.berisha@email.com",
                EmergencyContactName = "Вјолца Бериша",
                EmergencyContactPhone = "+38970666889",
                EmergencyRelationship = "Сопруга",
                BloodType = "B-",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-6),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient17,
                DoctorId = SeedIds.Doctor2,
                FirstName = "Ивана",
                LastName = "Димитриевска",
                NationalId = "0407993990011",
                SzboNumber = "SZBO-000017",
                BirthDate = new DateTime(1993, 7, 4),
                Gender = Gender.Female,
                City = "Stip",
                Address = "ул. Љубен Иванов 14",
                PostalCode = "1430",
                Phone = "+38975666999",
                Email = "ivana.dimitrievska@email.com",
                EmergencyContactName = "Александар Димитриевски",
                EmergencyContactPhone = "+38975666998",
                EmergencyRelationship = "Сопруг",
                BloodType = "A-",
                Allergies = "Јаткасти плодови",
                Status = PatientStatus.Chronic,
                RegistrationDate = now.AddDays(-5),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient18,
                DoctorId = SeedIds.Doctor4,
                FirstName = "Бојан",
                LastName = "Станковски",
                NationalId = "2202989001122",
                SzboNumber = "SZBO-000018",
                BirthDate = new DateTime(1989, 2, 22),
                Gender = Gender.Male,
                City = "Skopje",
                Address = "ул. Кузман Јосифовски Питу 3",
                PostalCode = "1000",
                Phone = "+38970777999",
                Email = "bojan.stankovski@email.com",
                EmergencyContactName = "Елена Станковска",
                EmergencyContactPhone = "+38970777998",
                EmergencyRelationship = "Сопруга",
                BloodType = "O+",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-4),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient19,
                DoctorId = SeedIds.Doctor4,
                FirstName = "Елизабета",
                LastName = "Павловска",
                NationalId = "1509975112233",
                SzboNumber = "SZBO-000019",
                BirthDate = new DateTime(1975, 9, 15),
                Gender = Gender.Female,
                City = "Gevgelija",
                Address = "ул. Солунска 17",
                PostalCode = "7000",
                Phone = "+38975888111",
                Email = "elizabeta.pavlovska@email.com",
                EmergencyContactName = "Зоран Павловски",
                EmergencyContactPhone = "+38975888112",
                EmergencyRelationship = "Сопруг",
                BloodType = "AB+",
                Allergies = "Нема",
                Status = PatientStatus.Inactive,
                RegistrationDate = now.AddDays(-3),
                IsDeleted = false
            },
            new()
            {
                Id = SeedIds.Patient20,
                DoctorId = SeedIds.Doctor4,
                FirstName = "Дејан",
                LastName = "Лазаревски",
                NationalId = "3011995223344",
                SzboNumber = "SZBO-000020",
                BirthDate = new DateTime(1995, 11, 30),
                Gender = Gender.Male,
                City = "Skopje",
                Address = "ул. Мито Хаџивасилев Јасмин 9",
                PostalCode = "1000",
                Phone = "+38970999222",
                Email = "dejan.lazarevski@email.com",
                EmergencyContactName = "Марија Лазаревска",
                EmergencyContactPhone = "+38970999223",
                EmergencyRelationship = "Сестра",
                BloodType = "A+",
                Allergies = "Нема",
                Status = PatientStatus.Active,
                RegistrationDate = now.AddDays(-2),
                IsDeleted = false
            }
        };

        // Idempotent expansion: older demo databases may already contain only the
        // original first few patients. Add the missing seeded patients without
        // duplicating existing records.
        var existingPatientIds = await context.Patients
            .Where(x => patients.Select(p => p.Id).Contains(x.Id))
            .Select(x => x.Id)
            .ToHashSetAsync(ct);

        var missingPatients = patients
            .Where(x => !existingPatientIds.Contains(x.Id))
            .ToList();

        if(missingPatients.Count > 0)
            await context.Patients.AddRangeAsync(missingPatients, ct);

await context.SaveChangesAsync(ct);
    }
}