using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Windows.Input;

namespace EHMR.Resources.Controls
{
    /// <summary>
    /// Search toolbar: search box + suggestions + pickers + action buttons.
    /// Tabs are intentionally not rendered (properties kept for binding compatibility).
    /// Grid column headers belong to SparkDataGridView, not here.
    /// </summary>
    public partial class SparkExplorerHeaderView : ContentView
    {
        private const string RefreshLabel = "Освежи";

        private double _responsiveScale = 1d;
        private double _lastResponsiveWidth = -1;

        public SparkExplorerHeaderView()
        {
            InitializeComponent();

            // Hook the default collection (bound collections are hooked in propertyChanged).
            Buttons.CollectionChanged+=OnButtonsChanged;
            RebuildButtonGroups();
        }

        // =====================================================================
        // BUTTON GROUPS
        // =====================================================================
        public ObservableCollection<SparkButtonItem> ActionButtons { get; } = new();

        public SparkButtonItem? ClearButton =>
            Buttons?.FirstOrDefault(x => IsRefresh(x));

        public bool HasClearButton => ClearButton is not null;

        private static bool IsRefresh(SparkButtonItem item) =>
            string.Equals(item.Label, RefreshLabel, StringComparison.OrdinalIgnoreCase);

        private void OnButtonsChanged(object? sender, NotifyCollectionChangedEventArgs e)
            => RebuildButtonGroups();

        private void RebuildButtonGroups()
        {
            ActionButtons.Clear();

            if(Buttons is not null)
            {
                foreach(var button in Buttons)
                {
                    if(!IsRefresh(button))
                        ActionButtons.Add(button);
                }
            }

            OnPropertyChanged(nameof(ClearButton));
            OnPropertyChanged(nameof(HasClearButton));
        }

        private void OnClearClicked(object? sender, EventArgs e)
        {
            var command = ClearButton?.Command;
            var parameter = ClearButton?.CommandParameter;

            if(command?.CanExecute(parameter)==true)
                command.Execute(parameter);
        }

        // =====================================================================
        // RESPONSIVE LAYOUT
        // =====================================================================
        private void OnHeaderSizeChanged(object? sender, EventArgs e)
        {
            ApplyResponsiveLayout();
        }

        private void ApplyResponsiveLayout()
        {
            var width = Width;
            if(width<=0||Math.Abs(width-_lastResponsiveWidth)<2)
                return;

            _lastResponsiveWidth=width;
            _responsiveScale=width>=1500 ? 1d
                : width>=1250 ? 0.94d
                : width>=1050 ? 0.88d
                : width>=900 ? 0.82d
                : 0.76d;

            var s = _responsiveScale;

            SecondaryToolbarGrid.Padding=new Thickness(0);
            SecondaryToolbarGrid.ColumnSpacing=8*s;
            SecondaryToolbarGrid.MinimumHeightRequest=64*s;

            HeaderSearchBox.HorizontalOptions=LayoutOptions.Fill;
            HeaderSearchBox.MinimumWidthRequest=0;
            HeaderSearchBox.Margin=new Thickness(0);

            CyrillicToggleLayout.WidthRequest=100*s;
            CyrillicToggleLayout.Spacing=4*s;
            CyrillicToggleLayout.IsVisible=ShowCyrillicToggle&&width>=900;

            ActionLayout.Spacing=4*s;

            foreach(var picker in PickerLayout.Children.OfType<FFPicker>())
            {
                picker.MinimumWidthRequest=Math.Max(100, 110*s);
                picker.Margin=new Thickness(0, 0, 8*s, 0);
            }

            // Buttons: the fixed "Освежи" one + the ones generated by BindableLayout.
            var buttons = ActionLayout.Children
                .SelectMany(c => c is HorizontalStackLayout h ? h.Children : new[] { c })
                .OfType<FFButton>();

            foreach(var button in buttons)
            {
                button.HeightRequest=44*s;
                button.ContentPadding=new Thickness(16*s, 0);
            }
        }

        // =====================================================================
        // VISIBILITY
        // =====================================================================
        #region Search / Tabs visibility

        public static readonly BindableProperty TabsVisibleProperty =
            BindableProperty.Create(nameof(TabsVisible), typeof(bool), typeof(SparkExplorerHeaderView), true);

        /// <summary>Kept for binding compatibility. Tabs are not rendered.</summary>
        public bool TabsVisible
        {
            get => (bool)GetValue(TabsVisibleProperty);
            set => SetValue(TabsVisibleProperty, value);
        }

        public static readonly BindableProperty SearchVisibleProperty =
            BindableProperty.Create(nameof(SearchVisible), typeof(bool), typeof(SparkExplorerHeaderView), true);

        public bool SearchVisible
        {
            get => (bool)GetValue(SearchVisibleProperty);
            set => SetValue(SearchVisibleProperty, value);
        }

        #endregion

        #region Tabs

        public static readonly BindableProperty TabsProperty =
            BindableProperty.Create(
                nameof(Tabs),
                typeof(ObservableCollection<SparkTabItem>),
                typeof(SparkExplorerHeaderView),
                defaultValueCreator: _ => new ObservableCollection<SparkTabItem>());

        /// <summary>Kept for binding compatibility. Tabs are not rendered.</summary>
        public ObservableCollection<SparkTabItem> Tabs
        {
            get => (ObservableCollection<SparkTabItem>)GetValue(TabsProperty);
            set => SetValue(TabsProperty, value);
        }

        #endregion

        #region Pickers

        public static readonly BindableProperty PickersProperty =
            BindableProperty.Create(
                nameof(Pickers),
                typeof(ObservableCollection<SparkPickerItem>),
                typeof(SparkExplorerHeaderView),
                defaultValueCreator: _ => new ObservableCollection<SparkPickerItem>());

        public ObservableCollection<SparkPickerItem> Pickers
        {
            get => (ObservableCollection<SparkPickerItem>)GetValue(PickersProperty);
            set => SetValue(PickersProperty, value);
        }

        #endregion

        #region Buttons

        public static readonly BindableProperty ButtonsProperty =
            BindableProperty.Create(
                nameof(Buttons),
                typeof(ObservableCollection<SparkButtonItem>),
                typeof(SparkExplorerHeaderView),
                defaultValueCreator: _ => new ObservableCollection<SparkButtonItem>(),
                propertyChanged: (b, o, n) =>
                {
                    var view = (SparkExplorerHeaderView)b;

                    if(o is ObservableCollection<SparkButtonItem> oldCol)
                        oldCol.CollectionChanged-=view.OnButtonsChanged;

                    if(n is ObservableCollection<SparkButtonItem> newCol)
                        newCol.CollectionChanged+=view.OnButtonsChanged;

                    view.RebuildButtonGroups();
                });

        /// <summary>
        /// Action buttons on the right. "Освежи" is rendered as the fixed green button,
        /// all others go through ActionButtons.
        /// NOTE: XAML bindings call SetValue directly (not this setter), so all
        /// hooking lives in propertyChanged above.
        /// </summary>
        public ObservableCollection<SparkButtonItem> Buttons
        {
            get => (ObservableCollection<SparkButtonItem>)GetValue(ButtonsProperty);
            set => SetValue(ButtonsProperty, value);
        }

        #endregion

        #region Search

        public static readonly BindableProperty ShowCyrillicToggleProperty =
            BindableProperty.Create(nameof(ShowCyrillicToggle), typeof(bool), typeof(SparkExplorerHeaderView), true);

        public bool ShowCyrillicToggle
        {
            get => (bool)GetValue(ShowCyrillicToggleProperty);
            set => SetValue(ShowCyrillicToggleProperty, value);
        }

        public static readonly BindableProperty UseCyrillicInputProperty =
            BindableProperty.Create(
                nameof(UseCyrillicInput),
                typeof(bool),
                typeof(SparkExplorerHeaderView),
                true,
                BindingMode.TwoWay);

        public bool UseCyrillicInput
        {
            get => (bool)GetValue(UseCyrillicInputProperty);
            set => SetValue(UseCyrillicInputProperty, value);
        }

        public static readonly BindableProperty SearchPlaceholderProperty =
            BindableProperty.Create(
                nameof(SearchPlaceholder),
                typeof(string),
                typeof(SparkExplorerHeaderView),
                "Пребарување...");

        public string SearchPlaceholder
        {
            get => (string)GetValue(SearchPlaceholderProperty);
            set => SetValue(SearchPlaceholderProperty, value);
        }

        public static readonly BindableProperty SearchCommandProperty =
            BindableProperty.Create(nameof(SearchCommand), typeof(ICommand), typeof(SparkExplorerHeaderView));

        /// <summary>Fired (debounced) when the user types in the search bar.</summary>
        public ICommand SearchCommand
        {
            get => (ICommand)GetValue(SearchCommandProperty);
            set => SetValue(SearchCommandProperty, value);
        }

        public static readonly BindableProperty SuggestionsProperty =
            BindableProperty.Create(
                nameof(Suggestions),
                typeof(System.Collections.IEnumerable),
                typeof(SparkExplorerHeaderView));

        public System.Collections.IEnumerable? Suggestions
        {
            get => (System.Collections.IEnumerable?)GetValue(SuggestionsProperty);
            set => SetValue(SuggestionsProperty, value);
        }

        public static readonly BindableProperty SuggestionTemplateProperty =
            BindableProperty.Create(nameof(SuggestionTemplate), typeof(DataTemplate), typeof(SparkExplorerHeaderView));

        public DataTemplate? SuggestionTemplate
        {
            get => (DataTemplate?)GetValue(SuggestionTemplateProperty);
            set => SetValue(SuggestionTemplateProperty, value);
        }

        public static readonly BindableProperty ShowSuggestionsProperty =
            BindableProperty.Create(
                nameof(ShowSuggestions),
                typeof(bool),
                typeof(SparkExplorerHeaderView),
                false,
                propertyChanged: (bindable, _, value) =>
                {
                    if(value is true)
                        ((SparkExplorerHeaderView)bindable).ShowSuggestionScrollbar();
                });

        public bool ShowSuggestions
        {
            get => (bool)GetValue(ShowSuggestionsProperty);
            set => SetValue(ShowSuggestionsProperty, value);
        }

        public static readonly BindableProperty SelectedSuggestionProperty =
            BindableProperty.Create(
                nameof(SelectedSuggestion),
                typeof(object),
                typeof(SparkExplorerHeaderView),
                null,
                BindingMode.TwoWay);

        public object? SelectedSuggestion
        {
            get => GetValue(SelectedSuggestionProperty);
            set => SetValue(SelectedSuggestionProperty, value);
        }

        public static readonly BindableProperty TrailingButtonProperty =
            BindableProperty.Create(nameof(TrailingButton), typeof(SparkButtonItem), typeof(SparkExplorerHeaderView));

        public SparkButtonItem TrailingButton
        {
            get => (SparkButtonItem)GetValue(TrailingButtonProperty);
            set => SetValue(TrailingButtonProperty, value);
        }

        private CancellationTokenSource? _searchDebounceCts;

        public static readonly BindableProperty SearchTextProperty =
            BindableProperty.Create(
                nameof(SearchText),
                typeof(string),
                typeof(SparkExplorerHeaderView),
                string.Empty,
                BindingMode.TwoWay,
                propertyChanged: (b, o, n) =>
                {
                    ((SparkExplorerHeaderView)b).OnSearchTextChanged((string)n);
                });

        public string SearchText
        {
            get => (string)GetValue(SearchTextProperty);
            set => SetValue(SearchTextProperty, value);
        }

        private async void OnSearchTextChanged(string newValue)
        {
            _searchDebounceCts?.Cancel();
            _searchDebounceCts=new CancellationTokenSource();
            var token = _searchDebounceCts.Token;

            try
            {
                await Task.Delay(250, token);
                if(!token.IsCancellationRequested&&SearchCommand?.CanExecute(newValue)==true)
                    SearchCommand.Execute(newValue);
            }
            catch(TaskCanceledException)
            {
                // expected on rapid typing
            }
        }

        #endregion

        // =====================================================================
        // SUGGESTION SCROLLBAR
        // =====================================================================
        private double _suggestionThumbStartY;

        private int SuggestionCount => Suggestions?.Cast<object>().Count()??0;

        private void ShowSuggestionScrollbar()
        {
            Dispatcher.DispatchDelayed(TimeSpan.FromMilliseconds(80), () =>
                UpdateSuggestionScrollThumb(0, Math.Min(Math.Max(0, SuggestionCount-1), 2)));
        }

        private void OnSuggestionListScrolled(object? sender, ItemsViewScrolledEventArgs e)
        {
            UpdateSuggestionScrollThumb(e.FirstVisibleItemIndex, e.LastVisibleItemIndex);
        }

        private void UpdateSuggestionScrollThumb(int firstVisibleIndex, int lastVisibleIndex)
        {
            var count = SuggestionCount;
            var railHeight = SuggestionScrollRail.Height;
            if(count<=0||railHeight<=0)
                return;

            var visibleCount = Math.Max(1, lastVisibleIndex-firstVisibleIndex+1);
            var thumbHeight = count<=visibleCount
                ? railHeight
                : Math.Max(30, railHeight*visibleCount/count);
            var maxTravel = Math.Max(0, railHeight-thumbHeight);
            var maxFirst = Math.Max(1, count-visibleCount);

            SuggestionScrollThumb.HeightRequest=thumbHeight;
            SuggestionScrollThumb.TranslationY=maxTravel*Math.Clamp(firstVisibleIndex/(double)maxFirst, 0, 1);
        }

        private void OnSuggestionThumbPanUpdated(object? sender, PanUpdatedEventArgs e)
        {
            var count = SuggestionCount;
            var maxTravel = Math.Max(0, SuggestionScrollRail.Height-SuggestionScrollThumb.Height);
            if(count<=1||maxTravel<=0)
                return;

            if(e.StatusType==GestureStatus.Started)
            {
                _suggestionThumbStartY=SuggestionScrollThumb.TranslationY;
                return;
            }

            if(e.StatusType!=GestureStatus.Running)
                return;

            var y = Math.Clamp(_suggestionThumbStartY+e.TotalY, 0, maxTravel);
            SuggestionScrollThumb.TranslationY=y;
            var targetIndex = (int)Math.Round((y/maxTravel)*(count-1));
            SuggestionList.ScrollTo(targetIndex, position: ScrollToPosition.Start, animate: false);
        }
    }
}